### ISSUE TITLE
Use source generators instead of code generation tasks

### ISSUE THREAD

**Issue by rdeago** [Buildvana/Buildvana.Sdk#148]
## Current version

1.0.0-alpha.20

## Background and motivation

Buildvana SDK uses compiled tasks to generate code. This was fine a couple years ago, when the project started, mostly because there was no choice. Now, however, we can accomplish the same results with source generators.

### Pros

- **Package size:** Only the source generator DLL would need to be included in the package. `Buildvana.Sdk.1.0.0-alpha.20.nupkg` is a tad over 22Mb; a version using source generators would most probably be well under 1Mb.
- **Performance:** Loading and executing our MSBuild tasks is rather costly in terms of both time and memory; source generators, on the other hand, are loaded by Roslyn as part of the well-tested and optimized analyzer infrastructure.
- **Simplification:** The same DLL can work with both Visual Studio (which uses the .NET Framework) and .NET SDK; no more custom MSBuild targets; no more chasing moving targets (pun intended) with every new version of every component involved (MSBuild, Roslyn, .NET SDK, Visual Studio); "one code to rule them all".
- **Better integration:** Source generators integrate naturally into the build process, no tricks, custom targets etc. needed.
- **Responsiveness:** Source generators (specifically, incremental generators) can update the generated code in real time in response to changes in inputs. For example, adding a `ThisAssemblyConstant` item in a project file would instantly make that constant available for use in code. Now, instead, an explicit rebuild of the project is needed to update generated code.

### Cons

- ~**Visual Basic compatibility:** Although incremental generators can declare the languages they work with, Visual Basic still doesn't seem to support generators at all.~ (actually, VB [has been supporting generators](https://github.com/dotnet/roslyn/pull/49139) since November 2020)
- ** F# compatibility:** the F# compiler does not support source generators. There are [type providers](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/) but, even assuming a type provider can generate assembly attributes, it would have to be written in F#.

## Proposed enhancement

Replace code generation tasks with source generators.

### Useful links

- [C# Source Generators](https://github.com/amis92/csharp-source-generators) by Amadeusz Sadowski
- [Source Generators Cookbook](https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md) in Roslyn documentation
- [Incremental generators](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md) in Roslyn documentation
- [Source generator updates: incremental generators (Exploring .NET 6 - Part 9)](https://andrewlock.net/exploring-dotnet-6-part-9-source-generator-updates-incremental-generators/) by Andrew Lock
- [Creating an incremental generator](https://andrewlock.net/creating-a-source-generator-part-1-creating-an-incremental-source-generator/) by Andrew Lock
- [Incremental Roslyn Source Generators In .NET 6: Code Sharing Of The Future – Part 1](https://www.thinktecture.com/en/net/roslyn-source-generators-introduction/) by Pawel Gerr
- [Using MSBuild Items and Properties in C# 9 Source Generators](https://platform.uno/blog/using-msbuild-items-and-properties-in-c-9-source-generators/) by Uno Platform Team
- [The pain points of C# source generators: February 2022 Update](https://turnerj.com/blog/csharp-source-generator-pain-points-february-2022-update) by James Turner

## Implementation proposals

- Incremental generators are to prefer over source generators, as they provide responsiveness to code (or, in our case, project file) changes.
- Configuration properties and items can most probably remain the same.
- Visual Basic support can be implemented from the beginning at almost no cost, as the necessary code can be copied over from current code generation tasks. When the VB compiler starts using generators, we'll be ready. Support can be removed later if the Roslyn team decides that VB is never going to use generators.

## Usage examples

Usage of the SDK would not change.

## Risks

- Modules currently relying on code generation tasks will lose compatibility with F# projects.

**Comment by rdeago** [comment]
Unfortunately we cannot pass MSBuild items (e.g. `ThisAssemblyConstant`) to source generators.

This is the relevant issue in Roslyn's repo: dotnet/roslyn#60595

A possible workaround could be to generate a file with the data we need and include it as an additional file, provided that:

- the additional file is regenerated only when necessary (we already have the logic for this, as code generation tasks are currently called only when relevant inputs change);
- the additional file is generated very early in the build process (reusing the existing logic should be fine here too);
- the additional file is generated _from MSBuild_, lest we have to implement _both_ a compiled task _and_ a source generator.

Going to research the last point at once.

**Comment by rdeago** [comment]
Why not ditch the ThisAssemblyClass module entirely and use @kzu's [ThisAssembly](https://www.clarius.org/ThisAssembly/) instead?

As for literal assembly attributes, their only use so far has been for `CLSCompliant` and `ComVisible`. A source generator for those two specific attributes is easy to write. And with that, code generation tasks would be gone for good.

**Comment by rdeago** [comment]
> Unfortunately we cannot pass MSBuild items (e.g. `ThisAssemblyConstant`) to source generators.

Turns out we can, by transforming them into `AdditionalFiles` items with custom metadata to recognize and extract them. See for example [this article](https://platform.uno/blog/using-msbuild-items-and-properties-in-c-9-source-generators/) (also linked in the original post 🤦‍♂️), as well as how @kzu does it ([MSBuild side](https://github.com/devlooped/ThisAssembly/blob/a900ce94c7d5e8d8b91bb2af48ef7c971aec968b/src/ThisAssembly.Constants/ThisAssembly.Constants.targets#L38) and [code generator side](https://github.com/devlooped/ThisAssembly/blob/a900ce94c7d5e8d8b91bb2af48ef7c971aec968b/src/ThisAssembly.Constants/ConstantsGenerator.cs#L20-L34)) in `ThisAssembly.Constants`.

I have a simple incremental generator that only handles `CLSCompliant` and `ComVisible` already working in a local copy of the SDK. That was a good exercise. Now I'm going to completely reimplement literal assembly attributes. Some of the code will be reusable to reimplement the ThisAssembly class too, without relying on @kzu's project (that doesn't have incremental generators and can only generate string constants).

**Comment by kzu** [comment]
Glad to take a PR to make ThisAssembly.Constants incremental 😉

**Comment by rdeago** [comment]
Original post edited to correct and update information about language compatibility.

(In short: no problem with VB; goodbye F#.)

Now back to work on source generators.
